# Generated by Django 2.1.7 on 2019-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('bill', models.IntegerField(default=170)),
            ],
            options={
                'db_table': 'company_bills',
            },
        ),
    ]
