# Generated by Django 2.1.7 on 2019-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bills',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
